// src/app/models/compliance-item.model.ts

/**
 * Enum for the status of a compliance item.
 */
export enum ComplianceStatus {
  TODO = 'TODO',
  UPCOMING = 'UPCOMING',
  COMPLETED = 'COMPLETED'
}

/**
 * Enum for the category of a compliance item.
 * This helps in filtering and organizing items.
 */
export enum ComplianceCategory {
  LICENSES_PERMITS = 'Licenses & Permits',
  TAXES = 'Taxes',
  EMPLOYEE_COMPLIANCE = 'Employee Compliance',
  HEALTH_SAFETY = 'Health & Safety',
  CORPORATE_GOVERNANCE = 'Corporate Governance',
  INSURANCE = 'Insurance',
  ENVIRONMENTAL = 'Environmental',
  OTHER = 'Other'
}

/**
 * Interface representing a single compliance item or task.
 * These items will be dynamically generated by the AI and stored in Firestore.
 */
export interface ComplianceItem {
  id: string; // Unique identifier for the compliance item (e.g., Firestore document ID)
  businessId: string; // The ID of the business this compliance item belongs to
  ownerId: string; // The Firebase UID of the owner for data security

  title: string; // A concise title for the compliance item (e.g., "Annual Business License Renewal")
  description: string; // Detailed description of what needs to be done
  category: ComplianceCategory; // Category of the compliance item (e.g., Taxes, Licenses & Permits)
  status: ComplianceStatus; // Current status (TODO, UPCOMING, COMPLETED)

  dueDate: Date | null; // The date when this item is due or was due
  nextReviewDate: Date | null; // The date when this item needs to be reviewed or is next due (for recurring items)
  frequency: string | null; // How often this item needs attention (e.g., "Annually", "Quarterly", "One-time")

  issuingAuthority: string; // The government body or organization responsible (e.g., "IRS", "Local Health Dept.")
  relevantLaws: string[]; // Array of relevant laws, rules, or regulations (e.g., ["OSHA 1910.1200"])
  requiredDocuments: string[]; // List of documents typically required for this compliance (e.g., "Application Form", "Inspection Report")

  // Optional fields for tracking and AI interaction
  notes?: string | null; // FIX: Allow 'null' in addition to 'string' or 'undefined'
  attachments?: { fileName: string; url: string; }[]; // Array of uploaded attachment details
  lastCompletedDate?: Date | null; // The last time this item was completed
  aiContext?: string; // A brief summary of the AI's reasoning for generating this item (for internal use/debugging)

  createdAt: Date; // Timestamp when the item was created by AI
  updatedAt: Date; // Timestamp when the item was last updated
}
